language: cpp
sudo: required
dist: trusty

before_install:
- test -n $CC  && unset CC
- test -n $CXX && unset CXX
- wget -O conda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
- chmod +x conda.sh
- bash conda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda

install:
- sudo apt-get install -y libopenmpi-dev openmpi-bin build-essential 
- conda install --yes atlas numpy scipy scikit-learn


script:
- cd $TRAVIS_BUILD_DIR
- mkdir build && cd build && cmake .. && make -j
- cd $TRAVIS_BUILD_DIR/tests/c_api_test && python test.py
- cd $TRAVIS_BUILD_DIR
- rm -rf build && mkdir build && cd build && cmake -DUSE_MPI=ON ..&& make -j

notifications:
  email: false

matrix:
  include:
    - compiler: gcc
    - compiler: clang
