# builds core artifacts, intended to be attached to releases
# or used by other workflows
name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# automatically cancel in-progress builds if another commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # tell scripts where to put artifacts
  BUILD_ARTIFACTSTAGINGDIRECTORY: '${{ github.workspace }}/artifacts'

jobs:
  archive:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 5
          persist-credentials: false
          submodules: true
      - name: Create source archive
        run: |
          mkdir -p "${BUILD_ARTIFACTSTAGINGDIRECTORY}"
          tar \
            -czvf \
            /tmp/LightGBM-complete_source_code_tar_gz.tar.gz \
            .
          mv \
            /tmp/LightGBM-complete_source_code_tar_gz.tar.gz \
            ${BUILD_ARTIFACTSTAGINGDIRECTORY}/
      - name: Create commit.txt
        shell: bash
        run: |
          git rev-parse HEAD > "${BUILD_ARTIFACTSTAGINGDIRECTORY}/commit.txt"
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: source-archive
          path: |
            ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}/commit.txt
            ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}/LightGBM-complete_source_code_tar_gz.tar.gz
          if-no-files-found: error
  all-build-jobs-successful:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - archive
    steps:
      - name: Note that all tests succeeded
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
