name: Link checks

on:
  # Run manually by clicking a button in the UI
  workflow_dispatch:
  # Run once a day at 8:00am UTC
  schedule:
    - cron: '0 8 * * *'

env:
  COMPILER: gcc
  OS_NAME: 'linux'
  TASK: 'check-links'

jobs:
  check-links:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 5
          persist-credentials: false
          submodules: false
      - name: Build docs
        run: |
          export CONDA=${HOME}/miniforge
          export PATH=${CONDA}/bin:${HOME}/.local/bin:${PATH}
          $GITHUB_WORKSPACE/.ci/setup.sh || exit 1
          $GITHUB_WORKSPACE/.ci/build-docs.sh || exit 1
      - name: Check links
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          args: >-
            --config=./docs/.lychee.toml
            --
            "**/*.rst"
            "**/*.md"
            "./R-package/**/*.Rd"
            "./docs/_build/html/*.html"
          fail: true
          failIfEmpty: true
