name: GitHub Actions

on: [push]

jobs:
  test:
    name: ${{ matrix.task }} (${{ matrix.os }}, ${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            task: r-package
            compiler: gcc
          - os: ubuntu-latest
            task: r-package
            compiler: clang
          - os: macOS-latest
            task: r-package
            compiler: gcc
          - os: macOS-latest
            task: r-package
            compiler: clang
          - os: windows-latest
            task: r-package
            compiler: MINGW
          - os: windows-latest
            task: r-package
            compiler: MSVC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Setup and run tests on Linux and macOS
        if: matrix.os != 'windows-latest'
        shell: bash
        env:
          COMPILER: "${{ matrix.compiler }}"
          CONDA_ENV: "test-env"
          GITHUB_ACTIONS: "true"
          TASK: "${{ matrix.task }}"
        run: |
          if [[ "${{ matrix.os }}" == "macOS-latest" ]]; then
              export OS_NAME="macos"
              export R_MAC_VERSION=3.6.3
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              export OS_NAME="linux"
              export R_TRAVIS_LINUX_VERSION=3.6.3-1bionic;
          fi
          if [ -z ${{ matrix.compiler }} ]; then
              export COMPILER=${{ matrix.compiler }}
          fi
          export BUILD_DIRECTORY="$GITHUB_WORKSPACE"
          export CONDA="$HOME/miniconda"
          export PATH="$CONDA/bin:${HOME}/.local/bin:$PATH"
          export LGB_VER=$(head -n 1 VERSION.txt)
          $GITHUB_WORKSPACE/.ci/setup.sh
          $GITHUB_WORKSPACE/.ci/test.sh
      - name: Use conda on Windows
        if: matrix.os == 'windows-latest'
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: false
      - name: Setup and run tests on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh -NonInteractive -ExecutionPolicy Bypass -Command "& '{0}'"
        env:
          COMPILER: "${{ matrix.compiler }}"
          GITHUB_ACTIONS: "true"
          TASK: "${{ matrix.task }}"
        run: |
          $env:BUILD_SOURCESDIRECTORY = $env:GITHUB_WORKSPACE
          conda init powershell
          & "$env:GITHUB_WORKSPACE/.ci/test_windows.ps1"
