name: Optional checks

on:
  pull_request:
    branches:
      - master

jobs:
  all-optional-checks-successful:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 5
          persist-credentials: false
          submodules: false
      - name: Check valgrind workflow
        shell: bash
        run: |
            # ref: https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#github-context
            PR_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
            echo "checking status for branch '${PR_BRANCH}'"
            ./.ci/check-workflow-status.sh \
                "${PR_BRANCH}" \
                'r_valgrind.yml' \
                ${{ github.event.number }}
